# cloudbuild.yaml
steps:
  # 1. 建立 Node.js 環境
  - name: 'node:20' # 或其他您偏好的 Node.js 版本
    entrypoint: 'npm'
    args: ['install']

  # 2. 建構專案
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']

  # 3. 將建構好的檔案上傳到 Cloud Storage
  # - name: 'gcr.io/cloud-builders/gsutil'
  #   args: ['-m', 'rsync', '-r', '-c', '-d', 'dist', 'gs://your-bucket-name'] # 替換為您的 bucket 名稱

# 可選: 設定觸發條件 (例如，當有新的程式碼推送到特定分支時觸發建構)
# triggers:
#   - id: 'my-vue3-vite5-build-trigger'
#     github:
#       owner: 'your-github-username'
#       name: 'your-repo-name'
#       push:
#         branch: 'main' # 或其他您想監控的分支

options:
  logging: CLOUD_LOGGING_ONLY