# cloudbuild.yaml
steps:
  # 1. 建立 Node.js 環境
  - name: 'node:20' # 或其他您偏好的 Node.js 版本
    entrypoint: 'npm'
    args: ['install']

  # 2. 建構專案
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']

  # 3. 壓縮 dist 目錄
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install', '-g', 'zip'] # 安裝 zip 工具 (如果尚未安裝)

  - name: 'node:20'
    entrypoint: 'zip'
    args: ['-r', 'dist.zip', 'dist']

  # 4. 將建構好的檔案上傳到 Artifact Registry
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk' # 使用 gcloud 指令
    entrypoint: 'bash'
    args:
    - '-c'
    - |
        gcloud artifacts generic upload --location=asia-east1 --repository=devops-test --source=dist.zip --package=my-vue-app --version=1.0.0

options:
  logging: CLOUD_LOGGING_ONLY