# cloudbuild.yaml
steps:
  # 1. 建立 Node.js 環境
  - name: 'node:20' # 或其他您偏好的 Node.js 版本
    entrypoint: 'npm'
    args: ['install']

  # 2. 建構專案
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']

  # 安裝zip套件，並在當前目錄透過zip壓縮dist檔案成dist.zip
  - name: 'ubuntu:latest'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
        apt update && apt install -y zip
        zip -r dist.zip dist/*
  
  # 4. 將建構好的檔案上傳到 Artifact Registry
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk' # 使用 gcloud 指令
    entrypoint: 'bash'
    args:
    - '-c'
    - |
        gcloud artifacts generic upload --location=asia-east1 --repository=devops-test --source=dist.zip --package=my-vue-app --version=1.0.0

options:
  logging: CLOUD_LOGGING_ONLY